title: mlocati - Michele Locati
email: mlocati@gmail.com
description: >
  A kind of personal list of notes for myself.
  Somebody found these notes quite useful, so I decided to share them.
baseurl: ""
url: "https://mlocati.github.io"
repository: mlocati/mlocati.github.io

markdown: kramdown

exclude:
 - /files/
 - /Gemfile
 - /Gemfile.lock

kramdown: 
  toc_levels: "2,3" 

collections:
  articles:
    output: true
defaults:
  -
    scope:
      path: ""
      type: articles
    values:
      layout: article

plugins:
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-coffeescript
 - jekyll-redirect-from
 - jekyll-coffeescript
